BATCH_SIZE = 10
EPOCHS = 50
INPUT_SHAPE = (64, 64, 64, 1)
DATASET_DIR_STL = "data/abc-dataset-stl"
DATASET_DIR_PLY = "data/abc-dataset-ply"
CHECKPOINT_PATH = "data/checkpoints/checkpoint.pt"
SAVED_MODEL_DIR = "data/saved-models"
POINT_CLOUD_DENSITY = 20000
VOXEL_DIM = 64
